# ä¸»ç«™å…¬å‘Š
notice:
  enable: true
  content: '<span id="tnxg_notice">Loading...</span><br>æ‚¨åœ¨é˜…è¯»åšæ–‡æ—¶è§†ä¸ºåŒæ„ä½¿ç”¨æ¡æ¬¾'

# å¤´åƒ
avatar:
  enable: true
  url: "https://q1.qlogo.cn/g?b=qq&nk=2271225249&s=640"
  rounded: true
  opacity: 1
  mickey_mouse: true
  status:
    enable: true
    emoji: "ğŸ¤”"
    message: "ç»†ç»†æ€ç´¢"

# å¯¼èˆª
menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: å­˜æ¡£
      path: /archives/
      icon: ri-archive-line ri-lg
    - type: æ ‡ç­¾
      path: /tags/
      icon: ri-bookmark-line ri-lg
    - type: shuoshuo
      path: /shuoshuo/
      icon: ri-message-2-line ri-lg
    - type: ç›¸å†Œ
      path: /albums/
      icon: ri-album-line ri-lg
  custom:
    title: "åå°"
    path: https://qexo.prts.top/
    icon: icon-settings-line

girls:
  enable: true
albums:
  enable: true

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri-men-line ri-lg
    color: dodgerblue

  - name: å‹é“¾æœ‹å‹åœˆ
    url: /friendcircle/
    icon: ri-group-2-line ri-lg
    color: green

  - name: å–œæ¬¢çš„å¥³å­©å­ä»¬
    url: /girls/
    icon: ri-women-line ri-lg
    color: hotpink

  - name: é¸£è°¢åå•
    url: /thanks/
    icon: ri-vip-diamond-line ri-lg
    color: orange

  - name: å¼€å¾€
    url: https://travellings.link/
    icon: ri-train-line ri-lg
    color: black

  - name: ä½¿ç”¨æ¡æ¬¾
    url: /policy/
    icon: ri-file-text-line ri-lg
    color: purple

anonymous_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/avatar/none.jpg

# èƒŒæ™¯å›¾
sidebar:
  src: /js/sidebar.js
  bg_image: https://images.weserv.nl/?blur=2&q=100&url=https://cdn.jsdelivr.net/gh/YunYouJun/cdn@master/img/bg/alpha-stars-timing-1.webp
  dark_bg_image: https://images.weserv.nl/?blur=2&q=100&url=https://cdn.jsdelivr.net/gh/YunYouJun/cdn@master/img/bg/dark-alpha-stars-timing-1.webp
  bg_position: bottom 1rem center

bg_image:
  enable: true
  url: https://prts.top/api/img/wallpaper/?type=cdn
  dark: https://images.weserv.nl/?blur=2&q=100&url=https://cdn.jsdelivr.net/gh/TNXG/blog@gh_pages/assets/images/a08b87d6277f9e2fa10549740f30e924b899f39e.jpg
  # blur: 30px
  opacity: 1

tagcloud:
    enable: false
    amount: 20

# å¤´éƒ¨å¼•ç”¨
head:
  css:
    master: "/assets/css/master.css"
    fontawesome: "https://npm.elemecdn.com/fontawesome-free@latest/css/all.css"
    RemixIcon: "https://npm.elemecdn.com/remixicon@latest/fonts/remixicon.css"
  js:
    base:
    async:
      # é»˜è®¤å¼•å…¥çš„å›¾æ ‡èµ„æºï¼Œä½¿ç”¨ iconfont
      JQuery: 'https://npm.elemecdn.com/jquery@latest/dist/jquery.js'
      iconfont: "https://at.alicdn.com/t/font_1140697_dxory92pb0h.js"
    defer:

favicon: /assets/images/favicon.png

# é™æ€èµ„æº
cdn:
  pre: https://npm.elemecdn.com/tnxg-blog@latest
vendors:
  host: 'https://npm.elemecdn.com/'

# å­—ä½“
font:
  serif:
    family: 'HarmonyOS_Sans'
    weight: 900
  sans_serif:
    family: 'HarmonyOS_Sans'
    weight: 400
  monospace:
    family: 'HarmonyOS_Sans'

# å…³äºæˆ‘
social:
  - name: QQ
    link: https://wpa.qq.com/msgrd?v=3&uin=2271225249&site=qq&menu=yes
    icon: icon-qq-line
    color: "#12B7F5"

  - name: GitHub
    link: https://github.com/TNXG
    icon: icon-github-line
    color: "#181717"

  - name: E-Mail
    link: mailto:mcminecraftmc@126.com
    icon: icon-mail-line
    color: "#8E71C1"

  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/user/home?id=515522946
    icon: icon-netease-cloud-music-line
    color: "#EE0000"

  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/175424674
    icon: icon-bilibili-line
    color: "#FF8EB3"

  - name: RSS
    link: /atom.xml
    icon: icon-rss-line
    color: "#FFA500"

# Bannerè®¾ç½®
banner:
  enable: true
  title: å¤©ç¿”çš„åšå®¢
  src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

mode: time

# çƒŸèŠ±
fireworks:
  enable: true
  colors:
    - "102, 167, 221"
    - "62, 131, 225"
    - "33, 78, 194"

# é¦–é¡µå¡ç‰‡ä¸æ–‡ç« å†…éƒ¨å›¾ç‰‡çš„æ»šåŠ¨æµ®ç°æ•ˆæœ
scrollreveal:
  enable: true
  targets:
    - .post-card
    - .post-content img

# é¼ æ ‡æŒ‡é’ˆ
cursor:
  enable: true
  default: https://npm.elemecdn.com/tnxg-blog@latest/assets/cursors/pointer.ani
  pointer: https://npm.elemecdn.com/tnxg-blog@latest/assets/cursors/link.ani
  text: https://npm.elemecdn.com/tnxg-blog@latest/assets/cursors/text.ani

# ä¿¡æ¯ï¼ˆæ˜¾ç¤ºæ–‡å­—ã€åˆ›å»ºæ—¶é—´ã€æ›´æ–°æ—¶é—´ã€ç§ç±»ã€æ ‡ç­¾ï¼‰
post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true
  tags: true

# é¡µé¢ä¿®æ”¹
post_edit:
  enable: true
  url: https://github.com/TNXG/blog/blob/master/source/

# ä»£ç é«˜äº®
codeblock:
  copy_btn: true
  prismjs:
    light: default
    dark: tomorrow

# è®¸å¯è¯
creative_commons:
  license: by-nc
  post: true
  language: deed.zh
  clipboard: true

# å›¾ç‰‡æ‡’åŠ è½½
lazyload:
  enable: true

# èµåŠ©
reward:
  enable: true
  icon: icon-hand-coin-line
  comment: "æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±ã€‚<br>I'm so cute. Please give me money."
  methods:
    - name: æ”¯ä»˜å®
      path: https://cdn.jsdelivr.net/gh/TNXG/TNXG/images/donate/alipay-qrcode.png
      color: "#00A3EE"
      icon: icon-alipay-line
    - name: QQ æ”¯ä»˜
      path: https://cdn.jsdelivr.net/gh/TNXG/TNXG/images/donate/qqpay-qrcode.png
      color: "#12B7F5"
      icon: icon-qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://cdn.jsdelivr.net/gh/TNXG/TNXG/images/donate/wechatpay-qrcode.png
      color: "#2DC100"
      icon: icon-wechat-pay-line

# é¡µè„š
footer:
  scripts:
    enable: true
  since: 2019
  icon:
    name: icon-cloud-line
    animated: true
    color: "#0078E7"
    url: /thanks/
    title: æœ¬åšå®¢åŸºäºHexo and Theme Yun
  powered:
    enable: false
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²åœ¨é£é›¨ä¸­è‰°éš¾è¿è¡Œäº†
    suffix: ğŸ˜¢
    start_time: "2019-08-12T12:00:00"
  custom_text: true

# ä¸€è¨€
say:
  enable: true
  api: /assets/data/yiyan.json
  src: /js/say.js
  hitokoto:
    enable: false
    api: https://v1.hitokoto.cn

# é»˜å“€
mourn:
  enable: false
  days:
    - "9-18"
    - "7-7"

# æœç´¢
local_search:
  enable: true
  src: /js/search/local-search.js

# twikooè¯„è®ºç³»ç»Ÿ
twikoo:
  enable: true
  envId: "https://api.twikoo.prts.top"
comment:
  enable: true
  tips:
    - è¯´äº›ä»€ä¹ˆï¼Ÿæ³¨æ„éµå®ˆå½“åœ°çš„æ³•å¾‹æ³•è§„å“¦ï¼
  candidates:
    - twikoo

baidu_push: true

# å­—æ•°ç»Ÿè®¡
wordcount:
  enable: true
  count: true
  time: true

# è¯äº‘
wordcloud:
  enable: true
  height: 350

# pjax
pjax:
  enable: false

